### ISSUE TITLE
Warning and different result

### ISSUE THREAD

**Issue by alpereninci** [poodarchu/AutoAssign#2]
I downloaded the pretrained model provided. During inference I'm getting the following warning. It results worse AP ~29. Also, could you upload the other models with different backbones that you share on the paper?

WARNING [02/12 13:37:59 c2.checkpoint.checkpoint]: 'backbone.top_block.p6.weight' has shape (256, 2048, 3, 3) in the checkpoint but (256, 256, 3, 3) in the model! Skipped.
[02/12 13:37:59 c2.checkpoint.checkpoint]: Some model parameters are not in the checkpoint:
  backbone.top_block.p6.weight

**Comment by poodarchu** [comment]
It may be caused by a recent update of cvpods, you can train your own model from scratch, and the result will match the results in paper.
