### ISSUE TITLE
loss norm

### ISSUE THREAD

**Issue by mightyzau** [poodarchu/AutoAssign#3]
Thank you for your excellent work. I have a question, what does "loss_norm" mean, this seems not mentioned in the original paper

**Comment by poodarchu** [comment]
it is a loss regularizer, which can be seen in many works, e.g., http://www.cbsr.ia.ac.cn/users/xiangyuzhu/papers/2019adaptiveface.pdf

**Comment by mightyzau** [comment]
> it is a loss regularizer, which can be seen in many works, e.g., http://www.cbsr.ia.ac.cn/users/xiangyuzhu/papers/2019adaptiveface.pdf

Thanks for your reply !

**Comment by mightyzau** [comment]
> it is a loss regularizer, which can be seen in many works, e.g., http://www.cbsr.ia.ac.cn/users/xiangyuzhu/papers/2019adaptiveface.pdf

I have another question. pos_weight is not detached in AutoAssign and FreeAnchor in `positive_bag_loss`, why ? When i tried detach, the performance drops.
