### ISSUE TITLE
Training is slow.

### ISSUE THREAD

**Issue by xuezu29** [poodarchu/AutoAssign#5]
I used AutoAssign to train my data set, but the speed of training was too slow.Is that normal?

**Comment by poodarchu** [comment]
put your log here.

**Comment by poodarchu** [comment]
it takes about 8 hours to train coco 1x on 2080ti x 8 .

**Comment by xuezu29** [comment]
> it takes about 8 hours to train coco 1x on 2080ti x 8 .

thanks a lot！when i change the settings, it works
but, I think there is something wrong with the loss curve after the training is completed. I don't know what is wrong with it.
model:resnet50+fpn,
 device:2080ti x 8 , 
SGD, 
lr:0.01 
epoch:100
lr step:60, 80
data: my own data set. 
![image](https://user-images.githubusercontent.com/10649774/126052926-d1abae15-00a3-4408-88e4-c2e91839403f.png)

**Comment by poodarchu** [comment]
are the results correct?

**Comment by xuezu29** [comment]
@poodarchu The result is already correct. very thankful!
